### PR TITLE
Add mifare classic technical overview video

### PR DESCRIPTION
**Pull request by kitsunehunter**
I post this from time to time in various servers so Bettse suggested it be PR'd into your collection of videos.

### CODE REVIEW

**Comment by kitsunehunter** [comment]
Feel free to ask me for details

**Comment by doegox** [comment]
Hello, [TheNotSoCivilEngr](https://www.youtube.com/@amihirata) channel is already listed in the Youtube channels section at the bottom actually, while the yearly list is more about talks given at conferences.

**Comment by kitsunehunter** [comment]
> Hello, [TheNotSoCivilEngr](https://www.youtube.com/@amihirata) channel is already listed in the Youtube channels section at the bottom actually, while the yearly list is more about talks given at conferences.

Yes it makes sense, main reason for this is the video isn't publically searchable, but yes, I do feel it's a little out of place as everything else is talks at conferences.

**Comment by doegox** [comment]
ha, but if here then it will become publicly searchable :D
what about adding a sub-bullet beside the mention of your channel?
(and generally speaking we could extend that section by pointing to the most relevant videos of each YT chan mentioned on the page. but that's future improvement...)

**Comment by doegox** [comment]
I mean
```diff
diff --git a/README.md b/README.md
index 7910325..c784875 100644
--- a/README.md
+++ b/README.md
@@ -134,6 +134,7 @@ Shamelessly inspired by [PalSec's awesome-sec-talks](https://github.com/PaulSec/
 * [Dangerous Things](https://www.youtube.com/@Dangerousthings)
 * [DeviantOllam](https://www.youtube.com/@DeviantOllam)
 * [TheNotSoCivilEngr](https://www.youtube.com/@amihirata)
+  * [MIFARE Classic Technical Video](https://www.youtube.com/watch?v=PzYS7aHWOuU)
 * [Penthertz](https://www.youtube.com/@Penthertz)
 * [MTools Tec](https://www.youtube.com/@mtoolstec)
 
```

**Pull request merged**
